version: "3.7"

services:
  arbot:
    image: jwstar/arbot
    network_mode: host
    restart: always
    container_name: arbot
    volumes:
      #aria2下载目录，默认
      - /root/downloads:/root/downloads
    environment:
      TZ: Asia/Shanghai
      API_ID: 11111
      API_HASH: 11111
      BOT_TOKEN: 11111:11111
      JSON_RPC_URL: http://11111:6800/jsonrpc
      JSON_RPC_TOKEN: 11111
      SEND_ID: 11111
      #      PROXY_IP:   #可选  代理ip
      #      PROXY_PORT:  #可选 代理端口
      UP_TELEGRAM: 'False' #是否上传电报