version: "3.7"
services:
  aria2bot:
    image: jwstar/aria2bot
    network_mode: host
    container_name: aria2bot
    restart: always
    volumes:
      - ./db:/app/db
      - /root/downloads:/root/downloads  # 下载目录
      - ./rclone:/root/.config/rclone  # 项目内的rclone配置目录
      - /qqqq:/qqqq
    build: .
    environment:
      TZ: Asia/Shanghai