#Telegram Bot配置
API_ID: xxxx
API_HASH: xxxxxxxx
BOT_TOKEN: xxxx:xxxxxxxxxxxx

#Telegram 管理员 ID
ADMIN_ID: 管理员ID
FORWARD_ID: 转发id

#默认是否上传到电报 true 或者 false
UP_TELEGRAM: false
#是否启用rclone上传到OneDrive
UP_ONEDRIVE: true

#rclone配置
RCLONE_REMOTE: onedrive #rclone配置的远程名称
RCLONE_PATH: /Downloads #OneDrive上的目标路径
#是否在成功上传到OneDrive后自动删除本地文件
AUTO_DELETE_AFTER_UPLOAD: true
#aria2c 设置
RPC_SECRET: xxxxxxx
RPC_URL: localhost:6800/jsonrpc

#代理ip 不需要则留空,目前代理只支持代理bot，aria2c 连接不支持代理目前
PROXY_IP:
PROXY_PORT: